[build-system]
requires      = ["setuptools>=68", "wheel"]
build-backend = "setuptools.backends.legacy:build"

[project]
name        = "tmq"
version     = "0.1.0"
description = "Transition Metal Quantum Chemistry Pipeline"
requires-python = ">=3.9"

dependencies = [
    "numpy",
    "pyscf",
    "qiskit",
    "qiskit-addon-sqd",
    "tangelo-gc",
]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov"]

[tool.setuptools.packages.find]
where = ["."]       # looks for packages (dirs with __init__.py) in project_root
include = ["tmq*"]  # include tmq and all sub-packages

[tool.pytest.ini_options]
testpaths    = ["tests"]
python_files = ["test_*.py"]