"""
Stage 7 (GQE runner, patch tooling, CLI dispatch) tests.

None of this needs CUDA-Q. The runner builds a command line and an
environment; the setup tool drives git. Both are testable without ever
launching a trainer, which is the point of keeping them free of solver
imports.
"""

from __future__ import annotations

import ast
import os
import pickle
import shutil
import subprocess
from pathlib import Path

import pytest

from quenais import cli
from quenais.config import GQE_SOLVERS, QISKIT_SOLVERS, SOLVERS, Config
from quenais.quantum import dispatch, gqe_runner, gqe_setup
from quenais.settings import GqeSettings


def _cfg(tmp_path, **kw):
    cfg = Config(molecule="LiH", basis="sto-3g", quantum_solver="gqe",
                 project_dir=str(tmp_path), **kw)
    return cfg.validate().make_dirs().load_geometry()


# ── Mandatory Hydra overrides ────────────────────────────────────────────

def test_command_carries_both_mandatory_overrides(tmp_path):
    """
    molecule=... and operator_pool.spec=... are both mandatory. Without the
    first, train.py silently loads n2.yaml and trains on N2 while the
    reported numbers claim to be yours.
    """
    cfg = _cfg(tmp_path)
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "train.py").write_text("")

    cmd = gqe_runner.build_command(cfg, repo)
    joined = " ".join(cmd)
    assert "molecule=dmet_embedding" in joined
    assert "operator_pool.spec=dmet_excitation" in joined


def test_command_pins_the_step2_path_absolutely(tmp_path):
    """
    Belt and braces against the hardcoded path in the shipped yaml, which
    silently pointed at a stale directory.
    """
    cfg = _cfg(tmp_path)
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "train.py").write_text("")

    cmd = gqe_runner.build_command(cfg, repo)
    match = [c for c in cmd if c.startswith("molecule.step2_pickle_path=")]
    assert len(match) == 1
    assert os.path.isabs(match[0].split("=", 1)[1])


def test_missing_train_entrypoint_is_reported(tmp_path):
    cfg = _cfg(tmp_path)
    repo = tmp_path / "repo"
    repo.mkdir()
    with pytest.raises(FileNotFoundError, match="train.py"):
        gqe_runner.build_command(cfg, repo)


# ── Subprocess environment ───────────────────────────────────────────────

def test_env_prepends_the_shim_directory(tmp_path):
    """
    The external factory does `import dmet_excitation_pool` as a top-level
    absolute import. The shim directory must come FIRST, so a stale copy
    inside the checkout cannot shadow the package's implementation.
    """
    cfg = _cfg(tmp_path)
    env = gqe_runner.build_env(cfg, tmp_path,
                               base_env={"PYTHONPATH": "/somewhere/else"})
    first = env["PYTHONPATH"].split(os.pathsep)[0]
    assert first.endswith("_gqe_shims")
    assert "/somewhere/else" in env["PYTHONPATH"], "existing entries kept"


def test_env_sets_the_cudaq_backend(tmp_path):
    """The external repo never calls set_target(), so this is the only lever."""
    cfg = _cfg(tmp_path, gqe=GqeSettings(cudaq_target="nvidia"))
    env = gqe_runner.build_env(cfg, tmp_path, base_env={})
    assert env["CUDAQ_DEFAULT_SIMULATOR"] == "nvidia"


def test_shim_modules_are_importable_from_the_shim_dir():
    """
    Import the shims exactly the way the subprocess will: by top-level
    name, with only the shim directory on the path.
    """
    code = (
        "import importlib.util, sys\n"
        "for name in ('dmet_molecule_adapter', 'dmet_excitation_pool'):\n"
        "    spec = importlib.util.find_spec(name)\n"
        "    assert spec is not None, name\n"
        "print('ok')\n"
    )
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join(
        [str(gqe_runner.SHIM_DIR)] + list(__import__("sys").path)
    )
    out = subprocess.run([__import__("sys").executable, "-c", code],
                         capture_output=True, text=True, env=env, timeout=60)
    assert out.returncode == 0, out.stderr
    assert "ok" in out.stdout


# ── Generated molecule config ────────────────────────────────────────────

def test_molecule_config_is_generated_not_shipped(tmp_path):
    cfg = _cfg(tmp_path)
    repo = tmp_path / "repo"
    repo.mkdir()

    path = gqe_runner._write_molecule_config(repo, cfg)
    assert path == repo / "configs" / "molecule" / "dmet_embedding.yaml"

    text = path.read_text()
    assert "_target_: dmet_molecule_adapter.load_from_dmet_pickle" in text
    assert os.path.abspath(cfg.step2_file) in text
    assert "Generated by" in text, "must be marked as generated"


def test_no_yaml_with_a_baked_path_is_shipped():
    """
    A configs/molecule/dmet_embedding.yaml inside the package would
    reintroduce the stale-path failure.
    """
    pkg_root = Path(gqe_runner.__file__).resolve().parents[1]
    strays = list(pkg_root.rglob("dmet_embedding.yaml"))
    assert not strays, f"shipped molecule config found: {strays}"


# ── Preflight ────────────────────────────────────────────────────────────

def test_preflight_rejects_a_missing_step2(tmp_path):
    cfg = _cfg(tmp_path)
    with pytest.raises(FileNotFoundError, match="embedding stage"):
        gqe_runner._preflight(cfg, tmp_path)


def test_preflight_rejects_another_molecules_step2(tmp_path, golden_dir):
    """Training on the wrong embedding yields a plausible, meaningless number."""
    cfg = _cfg(tmp_path)
    cfg.molecule = "ScH"
    shutil.copy(golden_dir / "LiH" / "step2_hamiltonian.pkl", cfg.step2_file)
    with pytest.raises(RuntimeError, match="different molecule"):
        gqe_runner._preflight(cfg, tmp_path)


# ── Patch tooling ────────────────────────────────────────────────────────

def test_patch_excludes_the_debug_config():
    """
    configs/trainer/default.yaml carried leftover debugging values. Baking
    them into the fork would silently override the package's own settings.
    """
    assert "configs/trainer/default.yaml" not in gqe_setup.PATCHED_FILES
    assert len(gqe_setup.PATCHED_FILES) == 3


def test_patch_includes_the_log_emitting_hunk():
    """
    train_pipeline.py is pure instrumentation but load-bearing: without it
    the visualisation stage has nothing to parse.
    """
    assert "gqe_qsci/train_pipeline.py" in gqe_setup.PATCHED_FILES


def test_upstream_sha_is_pinned():
    assert gqe_setup.UPSTREAM_SHA == "732c1ea"


def test_resolve_repo_reports_a_missing_path():
    with pytest.raises(FileNotFoundError, match="GQE_QSCI_REPO_PATH"):
        gqe_setup.resolve_repo(repo=None)


def test_resolve_repo_rejects_a_non_checkout(tmp_path):
    with pytest.raises(FileNotFoundError, match="train.py"):
        gqe_setup.resolve_repo(repo=str(tmp_path))


def test_verify_reports_an_unpatched_checkout(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "train.py").write_text("")
    problems = gqe_setup.verify_gqe_repo(repo)
    assert any("has not been applied" in p for p in problems)


def test_verify_strict_raises(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "train.py").write_text("")
    with pytest.raises(RuntimeError, match="not ready"):
        gqe_setup.verify_gqe_repo(repo, strict=True)


# ── Dispatch and CLI ─────────────────────────────────────────────────────

def test_dispatch_rejects_an_unknown_solver(tmp_path):
    cfg = _cfg(tmp_path)
    cfg.quantum_solver = "nope"
    with pytest.raises(ValueError, match="Unknown quantum_solver"):
        dispatch(cfg)


def test_cli_solver_choices_come_from_the_registry():
    """One list, not three. The CLI and Config must never disagree."""
    parser = cli.build_parser()
    action = next(a for a in parser._actions if a.dest == "solver")
    assert set(action.choices) == set(SOLVERS)
    assert "gqe" in action.choices


def test_cli_accepts_gqe(tmp_path):
    args = cli.build_parser().parse_args(
        ["--molecule", "LiH", "--basis", "sto-3g", "--solver", "gqe",
         "--project-dir", str(tmp_path)]
    )
    cfg = cli.build_config(args)
    assert cfg.quantum_solver == "gqe"
    assert cfg.is_gqe and not cfg.is_qiskit


def test_cli_passes_force_active_space_through(tmp_path):
    args = cli.build_parser().parse_args(
        ["--molecule", "ScH", "--basis", "sto-3g",
         "--force-active-space", "9", "10", "11", "12", "13", "14",
         "--project-dir", str(tmp_path)]
    )
    cfg = cli.build_config(args)
    assert cfg.asf.force_active_space == [9, 10, 11, 12, 13, 14]


def test_cli_rejects_an_unknown_step(tmp_path):
    with pytest.raises(SystemExit):
        cli.run_pipeline(["--steps", "9", "--project-dir", str(tmp_path)])


def test_step3_routes_through_dispatch():
    """Not through a hardcoded module path."""
    src = Path(cli.__file__).read_text()
    tree = ast.parse(src)
    run_step = next(n for n in tree.body
                    if isinstance(n, ast.FunctionDef) and n.name == "run_step")
    body = ast.dump(run_step)
    assert "dispatch" in body
    assert "quenais.quantum.solver" not in body, (
        "step 3 must not name a solver module directly"
    )


# ── Import isolation ─────────────────────────────────────────────────────

@pytest.mark.parametrize("module", ["gqe_runner", "gqe_setup"])
def test_runner_and_setup_have_no_solver_imports(module):
    """
    Both are imported during CLI dispatch, so neither may pull in a solver
    stack at module scope.
    """
    path = Path(getattr(gqe_runner if module == "gqe_runner" else gqe_setup,
                        "__file__"))
    tree = ast.parse(path.read_text())
    forbidden = {"cudaq", "tequila", "torch", "qiskit", "pyscf", "gqe_qsci"}
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            name = getattr(node, "module", None) or node.names[0].name
            assert name.split(".")[0] not in forbidden, f"{module}: {name}"


def test_quantum_package_init_is_import_light():
    """`from quenais.quantum import dispatch` must not import any solver."""
    import quenais.quantum

    tree = ast.parse(Path(quenais.quantum.__file__).read_text())
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            name = getattr(node, "module", None) or node.names[0].name
            assert not name.startswith("quenais.quantum."), (
                f"quantum/__init__.py imports {name} eagerly"
            )


# ── Self-test entry point ────────────────────────────────────────────────

def test_selftest_entry_point_is_importable():
    """Declared in setup.cfg's console_scripts, so it must exist."""
    from quenais import selftest

    assert callable(selftest.main)
    assert callable(selftest.run_selftest)


def test_selftest_does_not_claim_success_when_skipped(capsys=None):
    """
    A skip is not a pass. If PySCF is missing the physics never ran, and
    saying "install looks sound" would be actively misleading to a partner
    reporting results back.
    """
    from quenais import selftest

    src = Path(selftest.__file__).read_text()
    assert "elif total_skipped:" in src
    assert "does not verify the physics" in src


def test_all_console_scripts_resolve():
    """Every entry point in setup.cfg must import and be callable."""
    import configparser
    import importlib

    cfg_path = Path(__file__).resolve().parents[1] / "setup.cfg"
    parser = configparser.ConfigParser()
    parser.read(cfg_path)
    scripts = parser["options.entry_points"]["console_scripts"]

    for line in scripts.strip().splitlines():
        if "=" not in line:
            continue
        _name, target = (part.strip() for part in line.split("=", 1))
        module_path, func_name = target.split(":")
        module = importlib.import_module(module_path)
        assert callable(getattr(module, func_name)), target


def test_selftest_suppresses_third_party_output():
    """
    PySCF's logger and the ASF library both write past
    contextlib.redirect_stdout. Only an fd-level redirect covers code we do
    not own, so _quiet must use dup2 rather than a Python-level context.
    """
    from quenais import selftest

    src = Path(selftest.__file__).read_text()
    assert "dup2" in src, "_quiet must redirect at the file-descriptor level"
    assert "os.dup(1)" in src.replace("_os.", "os.")
